import sys
from sigmarsolver import SigmarsGarden, TileType

sg = SigmarsGarden()
# https://bits.ondrovo.com/sigmar/?seed=1774706658890
sg.setTile(0, 0, TileType.GOLD)
sg.setTile(1, 0, TileType.WATER)
sg.setTile(2, 0, TileType.DEATH)
sg.setTile(3, 0, TileType.QUICKSILVER)
sg.setTile(-1, 0, TileType.AIR)
sg.setTile(-2, 0, TileType.WATER)
sg.setTile(-3, 0, TileType.SALT)
sg.setTile(0, 1, TileType.WATER)
sg.setTile(1, 1, TileType.WATER)
sg.setTile(2, 1, TileType.LIFE)
sg.setTile(-1, 1, TileType.WATER)
sg.setTile(-2, 1, TileType.LIFE)
sg.setTile(-3, 1, TileType.WATER)
sg.setTile(-4, 1, TileType.FIRE)
sg.setTile(0, 2, TileType.AIR)
sg.setTile(1, 2, TileType.FIRE)
sg.setTile(2, 2, TileType.EARTH)
sg.setTile(-1, 2, TileType.AIR)
sg.setTile(-2, 2, TileType.DEATH)
sg.setTile(-3, 2, TileType.SILVER)
sg.setTile(-4, 2, TileType.FIRE)
sg.setTile(-5, 2, TileType.EARTH)
sg.setTile(0, 3, TileType.AIR)
sg.setTile(1, 3, TileType.EARTH)
sg.setTile(2, 3, TileType.FIRE)
sg.setTile(-1, 3, TileType.QUICKSILVER)
sg.setTile(-2, 3, TileType.AIR)
sg.setTile(-3, 3, TileType.SALT)
sg.setTile(-3, 4, TileType.SALT)
sg.setTile(-2, 4, TileType.EARTH)
sg.setTile(-3, 5, TileType.EARTH)
sg.setTile(0, -1, TileType.FIRE)
sg.setTile(1, -1, TileType.COPPER)
sg.setTile(2, -1, TileType.EARTH)
sg.setTile(3, -1, TileType.IRON)
sg.setTile(4, -1, TileType.DEATH)
sg.setTile(-1, -1, TileType.QUICKSILVER)
sg.setTile(-2, -1, TileType.QUICKSILVER)
sg.setTile(0, -2, TileType.TIN)
sg.setTile(1, -2, TileType.LIFE)
sg.setTile(2, -2, TileType.EARTH)
sg.setTile(3, -2, TileType.WATER)
sg.setTile(4, -2, TileType.LIFE)
sg.setTile(5, -2, TileType.FIRE)
sg.setTile(-1, -2, TileType.DEATH)
sg.setTile(-2, -2, TileType.EARTH)
sg.setTile(0, -3, TileType.SALT)
sg.setTile(-1, -3, TileType.QUICKSILVER)
sg.setTile(-2, -3, TileType.FIRE)
sg.setTile(1, -3, TileType.WATER)
sg.setTile(2, -3, TileType.AIR)
sg.setTile(3, -3, TileType.LEAD)
sg.setTile(3, -4, TileType.AIR)
sg.setTile(2, -4, TileType.AIR)
sg.setTile(3, -5, TileType.FIRE)

sol = sg.solve()
if not sol:
    print("Failed to solve!")
    sys.exit(1)

for i, move in enumerate(sol):
    print(f"{i:3d}) [{move.coord1} {TileType(move.t1).name}] <-> [{move.coord2} {TileType(move.t2).name}]")
