[build-system]
requires = ["scikit-build-core>=0.11"]
build-backend = "scikit_build_core.build"

[project]
name = "pysigmarsolver"
version = "0.0.1"
license = "GPL-3.0-only"
license-files = ["LICENSE"]
description="Python bindings for libsigmarsolver"
authors = [
  { name = "Joshua Barrass", email = "josh.barrass.work@gmail.com" },
]
requires-python = ">=3.8"

[tool.scikit-build]
minimum-version = "build-system.requires"
wheel.packages = ["sigmarsolver"]
wheel.py-api = "py3"
cmake.build-type = "Release"