name: Release Builds

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write  #  for release creation (svenstaro/upload-release-action)

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v6

      - name: Prepare Environment
        run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> ${GITHUB_ENV}

      - name: Build Library
        run: |
          mkdir -p build/linux
          cmake -B build/linux -DCMAKE_BUILD_TYPE=Release .
          cd build/linux
          make -j8

      - name: Upload Library
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release upload ${{ github.ref_name }} build/linux/libsigmarsolver.so
