name: Release Builds

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write  #  for release creation (svenstaro/upload-release-action)

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: gh release create --repo "${{ github.repository}}" --draft --title ${{ github.ref_name }} ${{ github.ref_name }}

  build:
    needs: create_release
    strategy:
      matrix:
        os: ["ubuntu-22.04", "windows-2025"]
        include:
          - buildsubdir: ""
          - os: "ubuntu-22.04"
            jobname: "Linux"
            libname: "libsigmarsolver.so"
          - os: "windows-2025"
            jobname: "Windows"
            buildsubdir: "Release/"
            libname: "sigmarsolver.dll"
    name: ${{ matrix.jobname }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v6

      - name: Prepare Environment
        shell: bash
        run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> ${GITHUB_ENV}

      - name: Configure CMake
        shell: bash
        run: |
          rm -rf build
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TEST_BINARIES=ON .

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Run Tests
        shell: bash
        run: |
          cd build/${{ matrix.buildsubdir }}
          shopt -s nullglob
          for test in ./test*; do
            if [ -x "$test" ] && [ -f "$test" ]; then
              echo "Running $test..."
              "$test" || exit 1
            fi
          done

      - name: Upload Library
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release upload ${{ github.ref_name }} build/${{ matrix.buildsubdir }}${{ matrix.libname }}
